export const projectsData = [
  {
    image: "./images/hanover.png",
    alt: "Hanover Football Club demo",
    title: "Hanover Football Club",
    date: "Sep 17, 2023",
    dateNum: "2023-09-17",
    id: 1,
    desc: "responsive splash page using HTML and CSS 🎉",
  },
  {
    image: "./images/super 7.png",
    alt: "Super 7 demo",
    title: "Super 7",
    date: "Sep 15, 2023",
    dateNum: "2023-09-15",
    id: 2,
    desc: "My first responsive site, check it out",
  },
  {
    image: "./images/restaurand ordering app.png",
    alt: "Restaurant Ordering App demo",
    title: "Restaurant Ordering App",
    date: "Sep 14, 2023",
    dateNum: "2023-09-14",
    id: 3,
    desc: "Order some food for your breakfast 🍔",
  },
  {
    image: "./images/anime picker.png",
    alt: "Anime Picker demo",
    title: "Anime Picker",
    date: "Sep 08, 2023",
    dateNum: "2023-09-08",
    id: 4,
    desc: "Get a New Anime Series Recommendation 😃",
  },
  {
    image: "./images/oldagram.png",
    alt: "Oldagram demo",
    title: "Oldagram",
    date: "Sep 04, 2023",
    dateNum: "2023-09-04",
    id: 5,
    desc: "Instagram Home page clone 🎉",
  },
  {
    image: "./images/unit convertor.png",
    alt: "Unit Converter demo",
    title: "Unit Converter",
    date: "Aug 31, 2023",
    dateNum: "2023-08-31",
    id: 6,
    desc: "Unit Converter App using HTML CSS and JS 💪",
  },
  {
    image: "./images/password generator.png",
    alt: "password generator demo",
    title: "Random Password Generator",
    date: "Aug 29, 2023",
    dateNum: "2023-08-29",
    id: 7,
    desc: "go and create own your password 😉",
  },
  {
    image: "./images/animal counter.png",
    alt: "Animal Counter App demo",
    title: "Animal Counter App",
    date: "Aug 27, 2023",
    dateNum: "2023-08-27",
    id: 8,
    desc: "Animal Counter App using HTML, CSS and JS",
  },
  {
    image: "./images/hometown.png",
    alt: "Hometown Homepage demo",
    title: "Hometown Homepage",
    date: "Aug 25, 2023",
    dateNum: "2023-08-25",
    id: 9,
    desc: "Project about my hometown 🙂",
  },
  {
    image: "./images/birthday gif site.png",
    alt: "The Birthday GIF Site demo",
    title: "The Birthday GIF Site",
    date: "Aug 25, 2023",
    dateNum: "2023-08-25",
    id: 10,
    desc: "In this site I am wishing hbd to my friend root",
  },
  {
    image: "./images/web agency hero.png",
    alt: "Web Agency Hero demo",
    title: "Web Agency Hero",
    date: "Aug 24, 2023",
    dateNum: "2023-08-24",
    id: 11,
    desc: "Yet another solo project 🏆",
  },
  {
    image: "./images/amazon product page.png",
    alt: "Amazon Product Page demo",
    title: "Amazon Product Page",
    date: "Aug 24, 2023",
    dateNum: "2023-08-24",
    id: 12,
    desc: "first solo project clone of Amazon Product Page",
  },
];
